name: claude-proxy-minimal
region: nyc1

services:
- name: api
  github:
    repo: richafltr/claude-proxy-minimal
    branch: main
    deploy_on_push: true
  
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  
  health_check:
    http_path: "/health"
    initial_delay_seconds: 15
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
    success_threshold: 1
  
  envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: GOOGLE_PROJECT_ID
    value: "gen-lang-client-0465895437"
  - key: GOOGLE_LOCATION
    value: "us-east5"
  - key: GOOGLE_SERVICE_ACCOUNT_JSON
    value: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZ2VuLWxhbmctY2xpZW50LTA0NjU4OTU0MzciLAogICJwcml2YXRlX2tleV9pZCI6ICJhNzVhZTVlYTBmZjk2ZjFiNzg5NzQzOGJmYzhkZTc4MWQzMWIyMWQ3IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURnU1RsaGNkODZJL0xzXG45NFBQNlBYUmVTdW0zS1N6eXhjRmhzWFBGTCtCRytkRnAyN2xnSFBTaDMxR0VJcFY1QTU5SnNicmo0YnBjWVFpXG41aWRKRUdVUFpXQjdQa1VxTHQ0RUhNZHZnbnJrb0dHUnNoVmNOZ0RicnBqRlBxSVJKT3VmNzZOSHBPZUVJVzFnXG5HTmN3UGt0NUxteWJGWmpibDhQR2xJWUd1enBYZU5MREQ5VlcwYnBKR25tSVJRMGFjdXN0cjZ5K1NycXFPeTlcbi91WGVPTDFYemEydWF5TGVjN1E5cG1rQ3JTbWNNQVlJdGcrU2RRYjNka0d2TDRFN0VGZE1jNUxDQzFDdGYxVVxuY3hJM2VXZWI0bkc5N09BMnh3S3ZGakJLUVBpUWZUTEJLWXFpaWM4dmlPUmI3SVBlTGNDUVU1cW4weUtHWnorXG5kZDUvVXR6aEFnTUJBQUVDZ2dFQUE3QnVOLzB4M0NFbSszYm8wOWEwbnhncXlGU2JrSGN1MHQzWFkyOUhGR2VnXG5YSkZycTVBaCs2VkxkSklONWdJWGNVRENHcFUreTVobTV2WW5xZUJUdHR0QjhWMDJPVDVVdVJJZnE0UFpMRmlcblNvWHJCSFNlQkNFSnUzRkh5OERwbFZLSmRBSHNSclAvZVJONnk5UnhPU0o5ZytqSUZSR1cwMzFYTjZrV3dEQ1xuSzhsL3FRdDJ6UWpVRkU2Q1gxaVExMGNiSVJ1UXMvaWhCTzlsNlgrM2tpV0dhSG95Z0p0ckNBd242VEVQVVdRXG5zWkNnbkVCUnh3b2g2a2lFN0x4WDVEQ1VHU3hjVGZ3clNHbERUaEJEQ2pLSUJmUzVkeTZ4UkR6cThoS01hZkI2XG5FWGdtWGNGU0ZBaXBVdHQ2Q3ZrNFZKM1Y4ejVKbm1Rc1VRSDgwOVFLQmdRRDNpS085VDczc2ZuYWVhUWswMlVVXG5pZTdOTXVCdkRQRXg1WGJyYjVYeGh6SHJCK1F4N1I0alI2T3k3aTk0VVV0V0FqYkZWZ2c4TjAySW5kM0h6b3VEXGl6U3Zpci95ZStoVkM3RDFpaEhtTitqdGVCR0JOSnNac2dGY3lWYW8vTTR3VEoyZEdUcFVka25jRlNBZzByc0JNXG5JOWRDZGFLckFCT2hoUXdxTDlFeWp3S0JnUURvUys1MEJTY052YXdQU0lBRHhJRWEyM3BYSk5wdGtRZ3J0cUZBXG5FQ3IyZGZmbTI1anJ3MllRTGt2NHR0RkhJUk8wUmk3NXFqemYvZEorKzFVc0kyZEhBSkMzbStKRy9DRU5hQ3hFXG5YQVRrY1pNMnNTOWZ2NGZrczVZY1BRQis5Z1lBNjBGSVRDcjQzdS9qMGpodHV3YXFzR0ZsZjVFK0Z5QkllQWJyXG40QXBkV3dLQmdEZ1ZicDh6N3ZtTnB5OENrR0E5NG0ySEdEMElXdWUxQkZxeDBuWGI2N2hCYkczQjJvZ3dLTi9cblU4WlJyRHFIbGRZWWNqK3hKRER4a1JzT1Y0VUVHUmU1NFVTQUliVUFuRk5nM2hiZFNHazR2dXFEWnlXSGM0YVhuMU1IRlFvUEQxRDdmTStsWjJYenJxZ0ZpV2FPN21pbzN6b0NYaEJiNEZWa3VCd2hXZU9BSWlEd0tCZ1FDbVhuSnhac1RWL29lWDJEY3pHRWVzSkJEYkJ6TG9YUEMrUFNDYXBTd3QxSHFxT1N5SGZFY0cwVm10dWE0c3dUXG5jQ1Y4MWQwZXNtTER2OFlGbCthTEhOeWwvTU1LYnlKaUZnRDBhd21qZG9sZXVidFJiaHRISWJyM1hLdE44eUtOXG5kQlkwSmxDbWZSZ0ZDbldpTVVDdk9CV2g4V01JdUg2OHd0Sml5MHoxT2dLQmdGdjFBQnJvYzg5SVltNXo2SHlEXG5lZFRCNXBMeDNmLzkwWldjMm1PT3pvRFpiS1kzTTloVXJXcXNaVnQvQXdRZ09FQmVOZzZqbXZicHdOV2xIZFBzXG5Ec1dzS0R4RThtdDV1RXNaUUhJRUFBd2JsZUNSZTZSN0lEQnp3YVJMVkQ1bDNmTGtRY1l1Q2RWTDdzZG5UdHdrXG44V3MzNVBnL2RFUVdFY3VlWFYyWTFQRFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImNsYXVkZS00LXByb3h5QGdlbi1sYW5nLWNsaWVudC0wNDY1ODk1NDM3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNTk5MjAyNTI2MDU5MDg1MTg3MSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvY2xhdWRlLTQtcHJveHklNDBnZW4tbGFuZy1jbGllbnQtMDQ2NTg5NTQzNy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQ=="
    type: SECRET
